name: Spring Boot CI
run-name: ${{ github.actor }} started CI

on:
  push:
    branches: [master]
    paths:
      - backend/spring-boot/**
  pull_request:
    branches: [master]
    paths:
      - backend/spring-boot/**

jobs:
  build:
    defaults:
      run:
        working-directory: backend/spring-boot

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven
      - name: Build
        run: mvn -B clean install -DskipTests
      - name: Unit tests
        run: mvn -B test
      - name: Integration tests
        run: mvn -B failsafe:integration-test
